// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW4laS3hDFnQYZjw6MJn_pCn76B7gF2zE',
    appId: '1:1011228341055:web:692baedea3c890bbec198a',
    messagingSenderId: '1011228341055',
    projectId: 'bire-398c6',
    authDomain: 'bire-398c6.firebaseapp.com',
    storageBucket: 'bire-398c6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVylCQNyLSsuFggW_unLqj7LdbPv8bReY',
    appId: '1:1011228341055:android:eb737b2d85ab089aec198a',
    messagingSenderId: '1011228341055',
    projectId: 'bire-398c6',
    storageBucket: 'bire-398c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm1sUiD_ey4M6V23eY9svEA0O6twHYWC8',
    appId: '1:1011228341055:ios:511123416176f8f2ec198a',
    messagingSenderId: '1011228341055',
    projectId: 'bire-398c6',
    storageBucket: 'bire-398c6.appspot.com',
    iosClientId: '1011228341055-p7kd4c889h7r1mnc7udn509cl3ldvs5v.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm1sUiD_ey4M6V23eY9svEA0O6twHYWC8',
    appId: '1:1011228341055:ios:511123416176f8f2ec198a',
    messagingSenderId: '1011228341055',
    projectId: 'bire-398c6',
    storageBucket: 'bire-398c6.appspot.com',
    iosClientId: '1011228341055-p7kd4c889h7r1mnc7udn509cl3ldvs5v.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );
}
